name: "freebayes_chunk"
description: Run freebayes on a sample chunk
keywords:
  - freebayes
  - chunk
  - variant caller
  - SNP
  - genotyping
  - bayesian
tools:
  - freebayes:
      description: Bayesian haplotype-based polymorphism discovery and genotyping
      homepage: https://github.com/freebayes/freebayes
      documentation: https://github.com/freebayes/freebayes
      tool_dev_url: https://github.com/freebayes/freebayes
      doi: "10.48550/arXiv.1207.3907"
      license: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing information on a region
        e.g. [ id:'test', single_end:false ]
  - sample_meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - region:
      type: string
      description: A region in which genotypes will be called (chrom:start-end)
  - bam:
      type: file
      description: a BAM file
      pattern: "*.{bam}"
  - bai:
      type: file
      description: Index for BAM file
      pattern: "*.{bai}"
  - bam_list:
      type: file
      description: A txt file in which all bam file names are described
      pattern: "*.list.txt"
  - genome_fasta:
      type: file
      description: The genome fasta file (not compressed)
      pattern: "*.{fa,fasta}"
  - genome_fasta_fai:
      type: file
      description: reference fasta file index
      pattern: "*.{fa,fasta}.fai"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF compressed with bgzip
      pattern: "*.{vcf.gz}"
  - index:
      type: file
      description: VCF indexed with tabix
      pattern: "*.{vcf.gz.tbi}"
  - versions:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@bunop"
