lint:
  actions_awsfulltest: False
  pipeline_todos: False
  files_exist: False
  nextflow_config: False
  files_unchanged:
    - .gitignore
    - .github/workflows/linting.yml
  actions_ci: False
  merge_markers: False
