repository_type: pipeline

nf_core_version: 3.1.1

lint:
  actions_awsfulltest: False
  pipeline_todos: False
  files_exist: False
  nextflow_config: False
  files_unchanged:
    - .gitignore
  actions_ci: False
  merge_markers: False
  multiqc_config: False
  pipeline_name_conventions: False
