name: "freebayes_splitbam"
description: Create a list of regions by splitting a reference based on the amount of data in bam files
keywords:
  - freebayes
  - splitbam
  - split_ref_by_bai_datasize
tools:
  - "freebayes":
      description: "Bayesian haplotype-based polymorphism discovery and genotyping"
      homepage: "https://github.com/freebayes/freebayes"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: "['MIT']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: path
      description: A list of BAM files
      pattern: "*.{bam}"
  - bai:
      type: path
      description: A list of BAM index files
      pattern: "*.{bai}"
  - genome_fasta:
      type: path
      description: The genome fasta file (not compressed)
      pattern: "*.{fa,fasta}"
  - genome_fasta_fai:
      type: file
      description: reference fasta file index
      pattern: "*.{fa,fasta}.fai"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - bam_list:
      type: file
      description: A list of each bam files
      pattern: "*.list.txt"
  - regions:
      type: file
      description: The regions file
      pattern: "*.regions.txt"

authors:
  - "@bunop"
