name: freebayes_multi
description: Run freebayes on multiple BAM files
keywords:
  - freebayes
  - multi
tools:
  - freebayes:
      description: Bayesian haplotype-based polymorphism discovery and genotyping
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ["MIT"]

input:
  - bam:
      type: path
      description: A list of *BAM files
      pattern: "*.{bam}"
  - genome_fasta:
      type: path
      description: The genome fasta file (not compressed)
      pattern: "*.{fa,fasta}"
  - genome_fasta_fai:
      type: file
      description: reference fasta file index
      pattern: "*.{fa,fasta}.fai"

output:
  - vcf:
      type: path
      description: |
        VCF compressed with bgzip (always all.fb.vcf.gz)
  - index:
      type: path
      description: |
        VCF indexed with tabix (always all.fb.vcf.gz.tbi)

  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@bunop"
