name: freebayes_multi
description: Run freebayes on multiple BAM files
keywords:
  - freebayes
  - multi
tools:
  - freebayes:
      description: Bayesian haplotype-based polymorphism discovery and genotyping
      homepage: https://github.com/freebayes/freebayes
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: path
      description: A list of BAM files
      pattern: "*.{bam}"
  - bai:
      type: path
      description: A list of BAM index files
      pattern: "*.{bai}"
  - genome_fasta:
      type: path
      description: The genome fasta file (not compressed)
      pattern: "*.{fa,fasta}"
  - genome_fasta_fai:
      type: file
      description: reference fasta file index
      pattern: "*.{fa,fasta}.fai"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: path
      description: |
        VCF compressed with bgzip (always all.fb.vcf.gz)
  - index:
      type: path
      description: |
        VCF indexed with tabix (always all.fb.vcf.gz.tbi)
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@bunop"
